### ISSUE TITLE
Create Flatpak App for Gearsystem

### ISSUE THREAD

**Issue by TomChapple** [drhelius/Gearsystem#93]
This emulator has been really awesome, especially on Linux, but I'm curious if distributing it as a [Flatpak application](https://www.flatpak.org/) can make it a bit more accessible. I have been using a (what appears to be) unofficial snap release, but it does have a nasty habit of pestering me to check audio permissions on startup. Setting up an official Flatpak release may not only resolve such odd permission requests but may allow for exploration of other releases of this kind is there is a different preference.

The main advantages I see of having a Flatpak release are:

* Packaging of dependencies (e.g. libglew) into one location rather than being a prerequisite
* Consistency in runtime environment across multiple Linux distributions
* Accessibility and discoverability of the application on common repositories such as [FlatHub](https://flathub.org/)
* Simple build process using a manifest and common existing build tools (autotools, cmake, etc)

I must admit, I am relatively new to the Flatpak development environment, so I'm not aware if there is any major constraint which would make such a release not worthwhile. For example, it would be interesting to see how the SDL gamecontrollers work inside a sandbox. At the very least though, I got a manifest together locally which _starts_ Gearsystem but is unable to initialise Glew.

Is there an interest to support such a release for this project?

**Comment by drhelius** [comment]
Thanks, it would be great for sure but, honestly, I don't have the time nor any experience with Flatpak.

I will leave this open though, just in case someone want to contribute it.

**Comment by TomChapple** [comment]
That's understandable.

I have been doing some experimentation into packaging a Flatpak application for this and managed to get it _packaged_, but it is receiving errors from both GTK3 and GLEW during initialisation. I'm struggling to interpret the exact cause, so I'm putting it up here in case someone recognises it.

GTK is of no help as `gtk_init_check` doesn't return any error codes, but GLEW does return an error code (despite reporting an "Unknown Error"): `GLEW_ERROR_NO_GLX_DISPLAY = 4`. This is returned [if `glXGetCurrentDisplay()` returns NULL](https://github.com/nigels-com/glew/blob/e1a80a9f12d7def202d394f46e44cfced1104bfb/auto/src/glew_init_glx.c#L25), which implies that there is no display for the current context. I'm not sure if this is a side-effect of Flatpak's sandboxing or not, so this will require some additional investigation.

For context, this is my current Flatpak configuration (assuming a working directory of `platforms/flatpak`):

```yaml
id: io.github.drhelius.Gearsystem
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: gearsystem
build-options:
  env:
    DEBUG: "1"
sdk-extensions:
  - org.freedesktop.Platform.GL
modules:
  - shared-modules/glu/glu-9.json
  - shared-modules/glew/glew.json
  - name: gearsystem
    buildsystem: simple
    build-commands:
      - make DEBUG=1
      - make install prefix="$FLATPAK_DEST"
    subdir: platforms/linux
    sources:
      - type: dir
        path: ../..
```

I tend to build it with `flatpak run org.flatpak.Builder --force-clean --user --install build-dir io.github.drhelius.Gearsystem.yml` and run it with `flatpak run io.github.drhelius.Gearsystem`.
